name: master_price_picker
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    get_it: ^4.0.4
    logger: ^0.9.2
    stacked: ^1.7.6
    stacked_services: ^0.5.4+2
    responsive_builder: ^0.2.0+2
    equatable: ^1.2.4
    web_scraper: ^0.0.6
    page_transition: ^1.1.7+6
    http:
    url_launcher:
    animated_splash_screen:
    #firebase
    firebase_core:
    firebase_auth:
    cloud_firestore:

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/
